apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cordum.fullname" . }}-config
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
data:
  safety.yaml: |-
{{ .Values.config.safety | indent 4 }}
  pools.yaml: |-
{{ .Values.config.pools | indent 4 }}
  timeouts.yaml: |-
{{ .Values.config.timeouts | indent 4 }}
